In [1]:
import numpy as np

In [2]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [3]:
print(np_baseball)

[180 215 210 210 188 176 209 200]


In [5]:
height_in = [100,20,30,60,78,90]

In [8]:
weight_lb = [300,40,80,45,78,98]

In [9]:
# height_in is available as a regular list

# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in

np_height_in = np.array(height_in)
# Print out np_height_in

print(np_height_in)
# Convert np_height_in to m: np_height_m
np_height_m = np_height_in*2.54/100

# Print np_height_m
print(np_height_m)

[100  20  30  60  78  90]
[2.54   0.508  0.762  1.524  1.9812 2.286 ]


In [10]:
# height_in and weight_lb are available as regular lists

# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb)*0.453592

# Calculate the BMI: bmi

bmi = np_weight_kg/np_height_m**2
# Print out bmi
print(bmi)

[21.09207018 70.30690061 62.49502277  8.78836258  9.01370521  8.50626699]


In [11]:
# height_in and weight_lb are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[False False False  True  True  True]
[8.78836258 9.01370521 8.50626699]


In [12]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [15]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball

print(type(np_baseball))
# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [16]:
#lets make a list of 3 columns having weight, height, and ages
baseball = [[[74, 60,20],[90,68,26],[80,63,55],[78,67,30],[82,72,28],[83,82,31]]]
baseball

[[[74, 60, 20],
  [90, 68, 26],
  [80, 63, 55],
  [78, 67, 30],
  [82, 72, 28],
  [83, 82, 31]]]

In [18]:
updated =[[[2, 1,1],[2, 1,1],[2, 1,1],[2, 1,1],[2, 1,1],[2, 1,1]]]
updated

[[[2, 1, 1], [2, 1, 1], [2, 1, 1], [2, 1, 1], [2, 1, 1], [2, 1, 1]]]

In [19]:
np_baseball = np.array(baseball)+np.array(updated)
np_baseball

array([[[76, 61, 21],
        [92, 69, 27],
        [82, 64, 56],
        [80, 68, 31],
        [84, 73, 29],
        [85, 83, 32]]])

In [20]:
#convert them into kg,m and age remains same
conversion = np.array([0.0254, 0.453592, 1])
conversion

array([0.0254  , 0.453592, 1.      ])

In [21]:
np_baseball_conversion = np_baseball*conversion
np_baseball_conversion

array([[[ 1.9304  , 27.669112, 21.      ],
        [ 2.3368  , 31.297848, 27.      ],
        [ 2.0828  , 29.029888, 56.      ],
        [ 2.032   , 30.844256, 31.      ],
        [ 2.1336  , 33.112216, 29.      ],
        [ 2.159   , 37.648136, 32.      ]]])

# numpy statistics

In [22]:
#Numbers of samples
height = np.round(np.random.normal(1.7,0.2,5000),2)
weight = np.round(np.random.normal(65,20,5000),2)
np_baseball = np.column_stack((height,weight))
np_baseball

array([[ 1.35, 70.43],
       [ 1.66, 47.88],
       [ 1.24, 66.74],
       ...,
       [ 1.76, 73.75],
       [ 1.88, 52.98],
       [ 1.84, 70.19]])

In [25]:
np.mean(np_baseball[:,0])


1.697532

In [26]:
np.median(np_baseball[:,0])

1.69

In [28]:
np.std(np_baseball[:,0])

0.19820037582204528

In [30]:
np.corrcoef(np_baseball[:,0])

1.0